// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceAmbercounterSvg = &fyne.StaticResource{
	StaticName: "amber_counter.svg",
	StaticContent: []byte(
		"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" enable-background=\"new 0 0 64 64\"><path d=\"m32 2c-16.568 0-30 13.432-30 30s13.432 30 30 30 30-13.432 30-30-13.432-30-30-30\" fill=\"#ffb300\"/></svg>\n"),
}
var resourceBlueGreycounterSvg = &fyne.StaticResource{
	StaticName: "blue-grey_counter.svg",
	StaticContent: []byte(
		"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" enable-background=\"new 0 0 64 64\"><path d=\"m32 2c-16.568 0-30 13.432-30 30s13.432 30 30 30 30-13.432 30-30-13.432-30-30-30\" fill=\"#546e7a\"/></svg>\n"),
}
